[package]
name = "bind_manager"
version = "0.1.0"
edition = "2021"
authors = ["Sophia Cross <scross@finnacloud.net>"]

[dependencies]
structopt = "0.3.26"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0"